spring.application.name=movie-app

# Veritabani baglanti adresi (localhost ve 3306 varsayilan MySQL portudur)
spring.datasource.url=jdbc:mysql://localhost:3306/mcp_movie_db?serverTimezone=UTC

# MySQL kullanici adin (Genelde varsayilan olarak root'tur)
spring.datasource.username=root

# MySQL sifren
spring.datasource.password=123456

# Sihirli ayar: Biz Java class'i yazacagiz, Spring Boot onu MySQL'de tabloya cevirecek
spring.jpa.hibernate.ddl-auto=update

# Arka planda calistirilan SQL kodlarini konsolda gormek icin
spring.jpa.show-sql=true

# TMDb API Ayarlari
tmdb.api.url=https://api.themoviedb.org/3
tmdb.api.key=${TMDB_API_KEY}

# Gemini API Ayarlari
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
gemini.api.key=${GEMINI_API_KEY}

# MONITORING (ACTUATOR) AYARLARI
# DevOps ekibinin sistemi izleyebilmesi icin health (saglik), info (bilgi) ve metrics (performans) uclarini aciyoruz
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
